repos:
- repo: local
  hooks:
  - id: black
    name: black[solvent]
    entry: poetry run black solvent
    language: system
    pass_filenames: false
    require_serial: true
    always_run: true
  - id: isort
    name: isort[solvent]
    entry: poetry run isort solvent
    language: system
    pass_filenames: false
    require_serial: true
    always_run: true
  - id: flake8
    name: flake8[solvent]
    entry: poetry run flake8 solvent
    language: system
    pass_filenames: false
    require_serial: true
    always_run: true
  - id: pyright
    name: pyright
    entry: poetry run pyright
    language: system
    pass_filenames: false
    require_serial: true
    always_run: true
