name: Format

on: [push]

jobs:
  format:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Black Formatting Check
        uses: psf/black@stable
        with:
          options: "--line-length 88"
          src: 'solvent'
      - name: Pyright Type check
        uses: jakebailey/pyright-action@v1
        with:
          project: 'pyproject.toml'
      - name: Linting check
        uses: TrueBrain/actions-flake8@master
        with:
          max_line_length: 88
          path: 'solvent'
