name: Format

on: [push]

jobs:
  format:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - name: Black Formatting Check
        uses: psf/black@stable
        with:
          src: 'solvent'
      - name: Pyright Type check
        uses: jakebailey/pyright-action@v1
        with:
          project: 'pyproject.toml'
          venv-path: '../.venv'
