name: Format

on: [push]

jobs:
  format:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Black Formatting Check
        uses: psf/black@stable
        with:
          src: 'solvent'
      - name: Pyright Type check
        uses: jakebailey/pyright-action@v1
        with:
          project: 'pyproject.toml'
