name: Format

on: [push]

jobs:
  format:
    name: Formatting + Type-checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - name: Black Formatting Check
        uses: psf/black@stable
        with:
          src: 'solvent'
      - run: poetry run isort solvent --check
      - run: poetry run pyright
