name: Test

on: [push]

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: '.venv'
      - run: poetry install
      - run: poetry run pytest tests
